/**
 * Regenerates `src/lib/themes/tweakcn-presets.ts` from tweakcn's `utils/theme-presets.ts`
 * (https://github.com/jnsahaj/tweakcn, Apache-2.0):
 *
 *   gh api repos/jnsahaj/tweakcn/contents/utils/theme-presets.ts \
 *     -H "Accept: application/vnd.github.raw" > /tmp/theme-presets.ts
 *   node apps/admin/scripts/import-tweakcn-presets.ts /tmp/theme-presets.ts <commit>
 *
 * Only data is copied: each preset's label and its light/dark overrides of tweakcn's default theme.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import vm from 'node:vm'

const [source, commit = 'unknown'] = process.argv.slice(2)
if (source === undefined)
  throw new Error('usage: import-tweakcn-presets.ts <theme-presets.ts> [commit]')

const code = readFileSync(source, 'utf8')
  .replace(/^import .*$/gm, '')
  .replace(/export const defaultPresets\s*:\s*Record<[^>]+>\s*=/, 'globalThis.presets =')
const sandbox: {
  presets?: Record<string, { label: string; styles: { light: object; dark: object } }>
} = {}
vm.runInNewContext(code, sandbox)
if (sandbox.presets === undefined) throw new Error('defaultPresets not found')

const presets = Object.fromEntries(
  Object.entries(sandbox.presets).map(([id, preset]) => [
    id,
    { label: preset.label, light: preset.styles.light, dark: preset.styles.dark },
  ]),
)
const out = fileURLToPath(new URL('../src/lib/themes/tweakcn-presets.ts', import.meta.url))
writeFileSync(
  out,
  `// Generated by scripts/import-tweakcn-presets.ts — do not edit.
// Theme presets from tweakcn (https://github.com/jnsahaj/tweakcn), commit ${commit}.
// Copyright tweakcn contributors, licensed under the Apache License 2.0 (see THIRD_PARTY_NOTICES.md).
import type { PresetDefinition } from './tokens.ts'

export const TWEAKCN_PRESETS: Readonly<Record<string, PresetDefinition>> = ${JSON.stringify(presets, null, 2)}
`,
)
console.log(`wrote ${Object.keys(presets).length} presets to ${out}`)
