import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'

/**
 * The public API surface of a package: the emitted declaration files reachable from its
 * `exports`, in a stable order. TypeScript 7 has no compiler API (ADR 0001), so instead of an
 * API extractor this follows the relative imports of `tsc`'s own `.d.ts` output.
 */
export function collectSurface(packageDir: string): { file: string; content: string }[] {
  const manifest = JSON.parse(readFileSync(path.join(packageDir, 'package.json'), 'utf8')) as {
    exports?: Record<string, { types?: string } | string>
  }
  const entries = Object.values(manifest.exports ?? {})
    .map((entry) => (typeof entry === 'string' ? undefined : entry.types))
    .filter((types): types is string => types !== undefined)
  const seen = new Map<string, string>()
  const queue = entries.map((types) => path.join(packageDir, types))
  while (queue.length > 0) {
    const file = queue.shift() as string
    if (seen.has(file)) continue
    const content = normalize(readFileSync(file, 'utf8'))
    seen.set(file, content)
    for (const specifier of relativeSpecifiers(content)) {
      const target = resolveDeclaration(path.dirname(file), specifier)
      if (target !== undefined && !seen.has(target)) queue.push(target)
    }
  }
  return [...seen.entries()]
    .map(([file, content]) => ({
      file: path.relative(packageDir, file).split(path.sep).join('/'),
      content,
    }))
    .sort((a, b) => a.file.localeCompare(b.file))
}

/** Relative module specifiers in `import … from`, `export … from`, and `import('…')`. */
export function relativeSpecifiers(source: string): string[] {
  const found = new Set<string>()
  for (const match of source.matchAll(/(?:from\s+|import\s*\(\s*)['"](\.{1,2}\/[^'"]+)['"]/g))
    if (match[1] !== undefined) found.add(match[1])
  return [...found]
}

function resolveDeclaration(dir: string, specifier: string): string | undefined {
  const base = path.join(dir, specifier)
  const candidates = [
    // tsc keeps `.ts` specifiers in declarations (rewriteRelativeImportExtensions).
    base.replace(/\.ts$/, '.d.ts'),
    base.replace(/\.js$/, '.d.ts'),
    base.replace(/\.mjs$/, '.d.mts'),
    `${base}.d.ts`,
    path.join(base, 'index.d.ts'),
  ]
  return candidates.find((candidate) => /\.d\.m?ts$/.test(candidate) && existsSync(candidate))
}

/** Drops what changes without an API change: source map comments and trailing whitespace. */
function normalize(source: string): string {
  return source
    .replace(/^\/\/# sourceMappingURL=.*$/gm, '')
    .split('\n')
    .map((line) => line.trimEnd())
    .join('\n')
    .trim()
}

/** The snapshot document of one package. */
export function renderSurface(name: string, files: { file: string; content: string }[]): string {
  const parts = [
    `# ${name} — API surface`,
    '',
    `Generated by \`pnpm api-surface:update\` from the declaration files reachable from the package's \`exports\` (plan 018.004). Review changes here like code: an added export is a minor version, a changed or removed one is breaking (\`feat(scope)!:\` with \`BREAKING CHANGE:\`).`,
    '',
  ]
  for (const { file, content } of files)
    parts.push(`## \`${file}\``, '', '```ts', content, '```', '')
  return `${parts.join('\n').trimEnd()}\n`
}
