import type { ModuleHonoEnv } from '@blixis-io/contracts'
import { defineModule } from '@blixis-io/kernel'
import { Hono } from 'hono'
import spec from '../openapi.json' with { type: 'json' }

/**
 * Serves the OpenAPI document of the Management API (ADR 0015) at `/api/v1/openapi.json`, in every
 * environment: it describes the public API and contains no secrets. Generated by
 * `pnpm openapi:generate`; CI fails when it is out of date.
 */
export const openApiModule = defineModule({
  meta: { name: '@blixis/api.openapi', version: '0.0.0' },
  rest: {
    path: '/openapi.json',
    app: new Hono<ModuleHonoEnv>().get('/', (c) =>
      c.json(spec, 200, { 'cache-control': 'public, max-age=300' }),
    ),
    operations: [
      {
        method: 'GET',
        path: '/',
        id: 'getOpenApiDocument',
        tag: 'Platform',
        summary: 'This OpenAPI 3.1 document',
        auth: false,
        responses: { 200: { description: 'The OpenAPI document' } },
      },
    ],
  },
})
